### ISSUE TITLE
TODO lijstje voor EHBDoorverwijzen

### ISSUE THREAD

**Issue by Timendus** [Timendus/tech-experiments#12]
* [ ] Content wat meer vullen zodat het een mooiere demo is (@Yannickdonners en Remy)
* [ ] CSS issue: `width` is meer dan 100% (@Timendus)
* [ ] Nieuwe naam verzinnen en overal doorvoeren (vergeet `title` niet)
* [ ] Zoek-feature
  * [ ] Werkend maken!
  * [ ] Fancy ontwerp maken en stylen
* [ ] Share button: design, styling, werkend maken
* [ ] Verzinnen wat we met het menu bovenaan willen
